-- SEO: 상위 10편 meta_description 150~160자 보강 (excerpt는 유지)
UPDATE posts SET meta_description = '피아노 과외 비용, 2026년 기준으로 정리했습니다. 대학생 과외 월 12만 원부터 전문 강사 월 40만 원까지, 레슨 시간·횟수·선생님 경력·방문 여부에 따라 달라지는 가격 기준과, 비용 대비 좋은 과외 고르는 법, 첫 상담·30분 체험 레슨 무료 혜택까지 알려드립니다.', updated_at = datetime('now') WHERE slug = 'piano-tutoring-cost';
UPDATE posts SET meta_description = '피아노 과외 선생님 고르는 법, 잘 치는 사람과 잘 가르치는 사람은 다릅니다. 전공과 경력 확인, 첫 레슨 계획의 구체성, 피드백 방식, 아이와의 궁합, 보강·운영 규칙까지. 첫 상담에서 반드시 확인해야 할 다섯 가지 기준을 레슨 경험에서 나온 예시와 함께 정리했습니다.', updated_at = datetime('now') WHERE slug = 'choosing-piano-tutor';
UPDATE posts SET meta_description = '피아노 학원 vs 과외, 우리 아이에게 맞는 선택은 무엇일까요. 체계적 시스템과 또래 활동이 강점인 학원, 맞춤 속도와 1:1 밀착 관리가 강점인 과외. 아이의 성향과 목표에 따른 선택 기준, 비용 비교, 두 가지를 함께 활용하는 현실적인 방법까지 실제 사례로 정리했습니다.', updated_at = datetime('now') WHERE slug = 'academy-vs-tutoring';
UPDATE posts SET meta_description = '초등 피아노 과외를 시작하기 전 부모가 알아야 할 모든 것입니다. 손 습관과 연습 루틴이 전부인 이 시기, 배우는 순서와 커리큘럼, 하루 적정 연습 시간, 부모는 어디까지 도와야 하는지, 방문 레슨 준비물까지. 초등 아이의 피아노 첫걸음을 실제 레슨 경험으로 안내합니다.', updated_at = datetime('now') WHERE slug = 'elementary-piano-tutoring';
UPDATE posts SET meta_description = '성인 피아노 과외, 왕초보여도 늦지 않은 이유를 알려드립니다. 악보를 처음 읽는 분도 기초부터 차근차근 배워 평균 3개월이면 간단한 곡 한 곡을 완성합니다. 이해력 덕분에 아이보다 빠른 입문 속도, 직장인이 퇴근 후 현실적으로 계속하는 연습법과 레슨 활용법까지 정리했습니다.', updated_at = datetime('now') WHERE slug = 'adult-piano-tutoring';
UPDATE posts SET meta_description = '피아노 과외 시간과 횟수, 어떻게 정하는 게 좋을까요. 주 1회 45분이 기본인 이유, 나이와 목표에 따른 45분·60분 선택 기준, 주 2회가 필요한 시기, 평일 저녁과 주말 시간대 선택 팁과 비용 차이까지. 우리 아이와 나에게 맞는 레슨 스케줄 설계 기준을 안내합니다.', updated_at = datetime('now') WHERE slug = 'tutoring-time-guide';
UPDATE posts SET meta_description = '서대문구 피아노 과외를 찾는다면, 이화여대 피아노과 재학생의 1:1 방문 레슨이 있습니다. 신촌·이대 앞·연희동·남가좌동·홍제동 등 서대문구 전역에서 아이가 집 피아노로 배우는 수업. 초등 취미부터 입시·콩쿠르까지, 첫 상담과 30분 체험 레슨은 무료로 진행하고 있습니다.', updated_at = datetime('now') WHERE slug = 'seodaemun-piano';
UPDATE posts SET meta_description = '마포구 피아노 과외, 직장인과 학부모를 위한 지역별 레슨 안내입니다. 합정·망원·상암·공덕·연남 방문 레슨, 퇴근 후 저녁 7~9시 성인 취미반부터 아이 방문 레슨까지. 이화여대 피아노과 재학생의 1:1 맞춤 수업으로, 첫 상담과 30분 체험 레슨은 무료로 진행합니다.', updated_at = datetime('now') WHERE slug = 'mapo-piano';
UPDATE posts SET meta_description = '이대 앞 피아노 레슨, 이화여대 피아노과 재학생 과외가 좋은 이유 세 가지를 자세히 알려드립니다. 가장 최근의 입시 경험, 전공 커리큘럼 그대로의 정확한 기초, 또래에 가까운 편한 소통. 합리적인 비용의 1:1 맞춤 레슨을 신촌·이대 일대에서 직접 만나보세요. 첫 상담은 무료입니다.', updated_at = datetime('now') WHERE slug = 'ewha-area-lesson';
UPDATE posts SET meta_description = '서울 피아노 과외, 이화여대 피아노과 재학생의 1:1 맞춤 레슨 안내입니다. 서대문구·마포구는 가정 방문으로, 강남·서초·송파·노원 등 서울 전역은 온라인 화상으로 진행합니다. 취미부터 입시·콩쿠르까지 지도하며, 지역별 레슨 방식과 첫 상담·30분 체험 무료 혜택까지 정리했습니다.', updated_at = datetime('now') WHERE slug = 'seoul-piano-tutoring';
