/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SitemapRouteImport } from './routes/sitemap'
import { Route as RssDotxmlRouteImport } from './routes/rss[.]xml'
import { Route as RobotsDottxtRouteImport } from './routes/robots[.]txt'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as LlmsDottxtRouteImport } from './routes/llms[.]txt'
import { Route as EditorialPolicyRouteImport } from './routes/editorial-policy'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ToolsIndexRouteImport } from './routes/tools/index'
import { Route as ResourcesIndexRouteImport } from './routes/resources/index'
import { Route as ResearchIndexRouteImport } from './routes/research/index'
import { Route as BlogIndexRouteImport } from './routes/blog/index'
import { Route as ToolsPianoLessonCostCalculatorRouteImport } from './routes/tools/piano-lesson-cost-calculator'
import { Route as ToolsPianoChordChartRouteImport } from './routes/tools/piano-chord-chart'
import { Route as ResourcesPianoPracticePlannerRouteImport } from './routes/resources/piano-practice-planner'
import { Route as ResourcesPianoLevelRoadmapRouteImport } from './routes/resources/piano-level-roadmap'
import { Route as ResearchPianoSearchDemandReport2026RouteImport } from './routes/research/piano-search-demand-report-2026'
import { Route as ResearchMethodologyRouteImport } from './routes/research/methodology'
import { Route as ResearchChangelogRouteImport } from './routes/research/changelog'
import { Route as Research2026SeoulPianoAcademyFeesRouteImport } from './routes/research/2026-seoul-piano-academy-fees'
import { Route as Research2025MusicPrivateEducationStatisticsRouteImport } from './routes/research/2025-music-private-education-statistics'
import { Route as MediaSplatRouteImport } from './routes/media/$'
import { Route as LessonsPrivateRouteImport } from './routes/lessons/private'
import { Route as LessonsHomeVisitRouteImport } from './routes/lessons/home-visit'
import { Route as LessonsChildrenRouteImport } from './routes/lessons/children'
import { Route as LessonsAdultRouteImport } from './routes/lessons/adult'
import { Route as LessonsAdmissionRouteImport } from './routes/lessons/admission'
import { Route as BlogCategoryIndexRouteImport } from './routes/blog/$category/index'
import { Route as BlogCategorySlugRouteImport } from './routes/blog/$category/$slug'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapRoute = SitemapRouteImport.update({
  id: '/sitemap',
  path: '/sitemap',
  getParentRoute: () => rootRouteImport,
} as any)
const RssDotxmlRoute = RssDotxmlRouteImport.update({
  id: '/rss.xml',
  path: '/rss.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const RobotsDottxtRoute = RobotsDottxtRouteImport.update({
  id: '/robots.txt',
  path: '/robots.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const LlmsDottxtRoute = LlmsDottxtRouteImport.update({
  id: '/llms.txt',
  path: '/llms.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const EditorialPolicyRoute = EditorialPolicyRouteImport.update({
  id: '/editorial-policy',
  path: '/editorial-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsIndexRoute = ToolsIndexRouteImport.update({
  id: '/tools/',
  path: '/tools/',
  getParentRoute: () => rootRouteImport,
} as any)
const ResourcesIndexRoute = ResourcesIndexRouteImport.update({
  id: '/resources/',
  path: '/resources/',
  getParentRoute: () => rootRouteImport,
} as any)
const ResearchIndexRoute = ResearchIndexRouteImport.update({
  id: '/research/',
  path: '/research/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsPianoLessonCostCalculatorRoute =
  ToolsPianoLessonCostCalculatorRouteImport.update({
    id: '/tools/piano-lesson-cost-calculator',
    path: '/tools/piano-lesson-cost-calculator',
    getParentRoute: () => rootRouteImport,
  } as any)
const ToolsPianoChordChartRoute = ToolsPianoChordChartRouteImport.update({
  id: '/tools/piano-chord-chart',
  path: '/tools/piano-chord-chart',
  getParentRoute: () => rootRouteImport,
} as any)
const ResourcesPianoPracticePlannerRoute =
  ResourcesPianoPracticePlannerRouteImport.update({
    id: '/resources/piano-practice-planner',
    path: '/resources/piano-practice-planner',
    getParentRoute: () => rootRouteImport,
  } as any)
const ResourcesPianoLevelRoadmapRoute =
  ResourcesPianoLevelRoadmapRouteImport.update({
    id: '/resources/piano-level-roadmap',
    path: '/resources/piano-level-roadmap',
    getParentRoute: () => rootRouteImport,
  } as any)
const ResearchPianoSearchDemandReport2026Route =
  ResearchPianoSearchDemandReport2026RouteImport.update({
    id: '/research/piano-search-demand-report-2026',
    path: '/research/piano-search-demand-report-2026',
    getParentRoute: () => rootRouteImport,
  } as any)
const ResearchMethodologyRoute = ResearchMethodologyRouteImport.update({
  id: '/research/methodology',
  path: '/research/methodology',
  getParentRoute: () => rootRouteImport,
} as any)
const ResearchChangelogRoute = ResearchChangelogRouteImport.update({
  id: '/research/changelog',
  path: '/research/changelog',
  getParentRoute: () => rootRouteImport,
} as any)
const Research2026SeoulPianoAcademyFeesRoute =
  Research2026SeoulPianoAcademyFeesRouteImport.update({
    id: '/research/2026-seoul-piano-academy-fees',
    path: '/research/2026-seoul-piano-academy-fees',
    getParentRoute: () => rootRouteImport,
  } as any)
const Research2025MusicPrivateEducationStatisticsRoute =
  Research2025MusicPrivateEducationStatisticsRouteImport.update({
    id: '/research/2025-music-private-education-statistics',
    path: '/research/2025-music-private-education-statistics',
    getParentRoute: () => rootRouteImport,
  } as any)
const MediaSplatRoute = MediaSplatRouteImport.update({
  id: '/media/$',
  path: '/media/$',
  getParentRoute: () => rootRouteImport,
} as any)
const LessonsPrivateRoute = LessonsPrivateRouteImport.update({
  id: '/lessons/private',
  path: '/lessons/private',
  getParentRoute: () => rootRouteImport,
} as any)
const LessonsHomeVisitRoute = LessonsHomeVisitRouteImport.update({
  id: '/lessons/home-visit',
  path: '/lessons/home-visit',
  getParentRoute: () => rootRouteImport,
} as any)
const LessonsChildrenRoute = LessonsChildrenRouteImport.update({
  id: '/lessons/children',
  path: '/lessons/children',
  getParentRoute: () => rootRouteImport,
} as any)
const LessonsAdultRoute = LessonsAdultRouteImport.update({
  id: '/lessons/adult',
  path: '/lessons/adult',
  getParentRoute: () => rootRouteImport,
} as any)
const LessonsAdmissionRoute = LessonsAdmissionRouteImport.update({
  id: '/lessons/admission',
  path: '/lessons/admission',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogCategoryIndexRoute = BlogCategoryIndexRouteImport.update({
  id: '/blog/$category/',
  path: '/blog/$category/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogCategorySlugRoute = BlogCategorySlugRouteImport.update({
  id: '/blog/$category/$slug',
  path: '/blog/$category/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/editorial-policy': typeof EditorialPolicyRoute
  '/llms.txt': typeof LlmsDottxtRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/rss.xml': typeof RssDotxmlRoute
  '/sitemap': typeof SitemapRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/lessons/admission': typeof LessonsAdmissionRoute
  '/lessons/adult': typeof LessonsAdultRoute
  '/lessons/children': typeof LessonsChildrenRoute
  '/lessons/home-visit': typeof LessonsHomeVisitRoute
  '/lessons/private': typeof LessonsPrivateRoute
  '/media/$': typeof MediaSplatRoute
  '/research/2025-music-private-education-statistics': typeof Research2025MusicPrivateEducationStatisticsRoute
  '/research/2026-seoul-piano-academy-fees': typeof Research2026SeoulPianoAcademyFeesRoute
  '/research/changelog': typeof ResearchChangelogRoute
  '/research/methodology': typeof ResearchMethodologyRoute
  '/research/piano-search-demand-report-2026': typeof ResearchPianoSearchDemandReport2026Route
  '/resources/piano-level-roadmap': typeof ResourcesPianoLevelRoadmapRoute
  '/resources/piano-practice-planner': typeof ResourcesPianoPracticePlannerRoute
  '/tools/piano-chord-chart': typeof ToolsPianoChordChartRoute
  '/tools/piano-lesson-cost-calculator': typeof ToolsPianoLessonCostCalculatorRoute
  '/blog/': typeof BlogIndexRoute
  '/research/': typeof ResearchIndexRoute
  '/resources/': typeof ResourcesIndexRoute
  '/tools/': typeof ToolsIndexRoute
  '/blog/$category/$slug': typeof BlogCategorySlugRoute
  '/blog/$category/': typeof BlogCategoryIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/editorial-policy': typeof EditorialPolicyRoute
  '/llms.txt': typeof LlmsDottxtRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/rss.xml': typeof RssDotxmlRoute
  '/sitemap': typeof SitemapRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/lessons/admission': typeof LessonsAdmissionRoute
  '/lessons/adult': typeof LessonsAdultRoute
  '/lessons/children': typeof LessonsChildrenRoute
  '/lessons/home-visit': typeof LessonsHomeVisitRoute
  '/lessons/private': typeof LessonsPrivateRoute
  '/media/$': typeof MediaSplatRoute
  '/research/2025-music-private-education-statistics': typeof Research2025MusicPrivateEducationStatisticsRoute
  '/research/2026-seoul-piano-academy-fees': typeof Research2026SeoulPianoAcademyFeesRoute
  '/research/changelog': typeof ResearchChangelogRoute
  '/research/methodology': typeof ResearchMethodologyRoute
  '/research/piano-search-demand-report-2026': typeof ResearchPianoSearchDemandReport2026Route
  '/resources/piano-level-roadmap': typeof ResourcesPianoLevelRoadmapRoute
  '/resources/piano-practice-planner': typeof ResourcesPianoPracticePlannerRoute
  '/tools/piano-chord-chart': typeof ToolsPianoChordChartRoute
  '/tools/piano-lesson-cost-calculator': typeof ToolsPianoLessonCostCalculatorRoute
  '/blog': typeof BlogIndexRoute
  '/research': typeof ResearchIndexRoute
  '/resources': typeof ResourcesIndexRoute
  '/tools': typeof ToolsIndexRoute
  '/blog/$category/$slug': typeof BlogCategorySlugRoute
  '/blog/$category': typeof BlogCategoryIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/editorial-policy': typeof EditorialPolicyRoute
  '/llms.txt': typeof LlmsDottxtRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/rss.xml': typeof RssDotxmlRoute
  '/sitemap': typeof SitemapRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/lessons/admission': typeof LessonsAdmissionRoute
  '/lessons/adult': typeof LessonsAdultRoute
  '/lessons/children': typeof LessonsChildrenRoute
  '/lessons/home-visit': typeof LessonsHomeVisitRoute
  '/lessons/private': typeof LessonsPrivateRoute
  '/media/$': typeof MediaSplatRoute
  '/research/2025-music-private-education-statistics': typeof Research2025MusicPrivateEducationStatisticsRoute
  '/research/2026-seoul-piano-academy-fees': typeof Research2026SeoulPianoAcademyFeesRoute
  '/research/changelog': typeof ResearchChangelogRoute
  '/research/methodology': typeof ResearchMethodologyRoute
  '/research/piano-search-demand-report-2026': typeof ResearchPianoSearchDemandReport2026Route
  '/resources/piano-level-roadmap': typeof ResourcesPianoLevelRoadmapRoute
  '/resources/piano-practice-planner': typeof ResourcesPianoPracticePlannerRoute
  '/tools/piano-chord-chart': typeof ToolsPianoChordChartRoute
  '/tools/piano-lesson-cost-calculator': typeof ToolsPianoLessonCostCalculatorRoute
  '/blog/': typeof BlogIndexRoute
  '/research/': typeof ResearchIndexRoute
  '/resources/': typeof ResourcesIndexRoute
  '/tools/': typeof ToolsIndexRoute
  '/blog/$category/$slug': typeof BlogCategorySlugRoute
  '/blog/$category/': typeof BlogCategoryIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/editorial-policy'
    | '/llms.txt'
    | '/pricing'
    | '/privacy'
    | '/robots.txt'
    | '/rss.xml'
    | '/sitemap'
    | '/sitemap.xml'
    | '/lessons/admission'
    | '/lessons/adult'
    | '/lessons/children'
    | '/lessons/home-visit'
    | '/lessons/private'
    | '/media/$'
    | '/research/2025-music-private-education-statistics'
    | '/research/2026-seoul-piano-academy-fees'
    | '/research/changelog'
    | '/research/methodology'
    | '/research/piano-search-demand-report-2026'
    | '/resources/piano-level-roadmap'
    | '/resources/piano-practice-planner'
    | '/tools/piano-chord-chart'
    | '/tools/piano-lesson-cost-calculator'
    | '/blog/'
    | '/research/'
    | '/resources/'
    | '/tools/'
    | '/blog/$category/$slug'
    | '/blog/$category/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/admin'
    | '/editorial-policy'
    | '/llms.txt'
    | '/pricing'
    | '/privacy'
    | '/robots.txt'
    | '/rss.xml'
    | '/sitemap'
    | '/sitemap.xml'
    | '/lessons/admission'
    | '/lessons/adult'
    | '/lessons/children'
    | '/lessons/home-visit'
    | '/lessons/private'
    | '/media/$'
    | '/research/2025-music-private-education-statistics'
    | '/research/2026-seoul-piano-academy-fees'
    | '/research/changelog'
    | '/research/methodology'
    | '/research/piano-search-demand-report-2026'
    | '/resources/piano-level-roadmap'
    | '/resources/piano-practice-planner'
    | '/tools/piano-chord-chart'
    | '/tools/piano-lesson-cost-calculator'
    | '/blog'
    | '/research'
    | '/resources'
    | '/tools'
    | '/blog/$category/$slug'
    | '/blog/$category'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admin'
    | '/editorial-policy'
    | '/llms.txt'
    | '/pricing'
    | '/privacy'
    | '/robots.txt'
    | '/rss.xml'
    | '/sitemap'
    | '/sitemap.xml'
    | '/lessons/admission'
    | '/lessons/adult'
    | '/lessons/children'
    | '/lessons/home-visit'
    | '/lessons/private'
    | '/media/$'
    | '/research/2025-music-private-education-statistics'
    | '/research/2026-seoul-piano-academy-fees'
    | '/research/changelog'
    | '/research/methodology'
    | '/research/piano-search-demand-report-2026'
    | '/resources/piano-level-roadmap'
    | '/resources/piano-practice-planner'
    | '/tools/piano-chord-chart'
    | '/tools/piano-lesson-cost-calculator'
    | '/blog/'
    | '/research/'
    | '/resources/'
    | '/tools/'
    | '/blog/$category/$slug'
    | '/blog/$category/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRoute
  EditorialPolicyRoute: typeof EditorialPolicyRoute
  LlmsDottxtRoute: typeof LlmsDottxtRoute
  PricingRoute: typeof PricingRoute
  PrivacyRoute: typeof PrivacyRoute
  RobotsDottxtRoute: typeof RobotsDottxtRoute
  RssDotxmlRoute: typeof RssDotxmlRoute
  SitemapRoute: typeof SitemapRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  LessonsAdmissionRoute: typeof LessonsAdmissionRoute
  LessonsAdultRoute: typeof LessonsAdultRoute
  LessonsChildrenRoute: typeof LessonsChildrenRoute
  LessonsHomeVisitRoute: typeof LessonsHomeVisitRoute
  LessonsPrivateRoute: typeof LessonsPrivateRoute
  MediaSplatRoute: typeof MediaSplatRoute
  Research2025MusicPrivateEducationStatisticsRoute: typeof Research2025MusicPrivateEducationStatisticsRoute
  Research2026SeoulPianoAcademyFeesRoute: typeof Research2026SeoulPianoAcademyFeesRoute
  ResearchChangelogRoute: typeof ResearchChangelogRoute
  ResearchMethodologyRoute: typeof ResearchMethodologyRoute
  ResearchPianoSearchDemandReport2026Route: typeof ResearchPianoSearchDemandReport2026Route
  ResourcesPianoLevelRoadmapRoute: typeof ResourcesPianoLevelRoadmapRoute
  ResourcesPianoPracticePlannerRoute: typeof ResourcesPianoPracticePlannerRoute
  ToolsPianoChordChartRoute: typeof ToolsPianoChordChartRoute
  ToolsPianoLessonCostCalculatorRoute: typeof ToolsPianoLessonCostCalculatorRoute
  BlogIndexRoute: typeof BlogIndexRoute
  ResearchIndexRoute: typeof ResearchIndexRoute
  ResourcesIndexRoute: typeof ResourcesIndexRoute
  ToolsIndexRoute: typeof ToolsIndexRoute
  BlogCategorySlugRoute: typeof BlogCategorySlugRoute
  BlogCategoryIndexRoute: typeof BlogCategoryIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap': {
      id: '/sitemap'
      path: '/sitemap'
      fullPath: '/sitemap'
      preLoaderRoute: typeof SitemapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rss.xml': {
      id: '/rss.xml'
      path: '/rss.xml'
      fullPath: '/rss.xml'
      preLoaderRoute: typeof RssDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/robots.txt': {
      id: '/robots.txt'
      path: '/robots.txt'
      fullPath: '/robots.txt'
      preLoaderRoute: typeof RobotsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/llms.txt': {
      id: '/llms.txt'
      path: '/llms.txt'
      fullPath: '/llms.txt'
      preLoaderRoute: typeof LlmsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/editorial-policy': {
      id: '/editorial-policy'
      path: '/editorial-policy'
      fullPath: '/editorial-policy'
      preLoaderRoute: typeof EditorialPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/': {
      id: '/tools/'
      path: '/tools'
      fullPath: '/tools/'
      preLoaderRoute: typeof ToolsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resources/': {
      id: '/resources/'
      path: '/resources'
      fullPath: '/resources/'
      preLoaderRoute: typeof ResourcesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/research/': {
      id: '/research/'
      path: '/research'
      fullPath: '/research/'
      preLoaderRoute: typeof ResearchIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/piano-lesson-cost-calculator': {
      id: '/tools/piano-lesson-cost-calculator'
      path: '/tools/piano-lesson-cost-calculator'
      fullPath: '/tools/piano-lesson-cost-calculator'
      preLoaderRoute: typeof ToolsPianoLessonCostCalculatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/piano-chord-chart': {
      id: '/tools/piano-chord-chart'
      path: '/tools/piano-chord-chart'
      fullPath: '/tools/piano-chord-chart'
      preLoaderRoute: typeof ToolsPianoChordChartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resources/piano-practice-planner': {
      id: '/resources/piano-practice-planner'
      path: '/resources/piano-practice-planner'
      fullPath: '/resources/piano-practice-planner'
      preLoaderRoute: typeof ResourcesPianoPracticePlannerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resources/piano-level-roadmap': {
      id: '/resources/piano-level-roadmap'
      path: '/resources/piano-level-roadmap'
      fullPath: '/resources/piano-level-roadmap'
      preLoaderRoute: typeof ResourcesPianoLevelRoadmapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/research/piano-search-demand-report-2026': {
      id: '/research/piano-search-demand-report-2026'
      path: '/research/piano-search-demand-report-2026'
      fullPath: '/research/piano-search-demand-report-2026'
      preLoaderRoute: typeof ResearchPianoSearchDemandReport2026RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/research/methodology': {
      id: '/research/methodology'
      path: '/research/methodology'
      fullPath: '/research/methodology'
      preLoaderRoute: typeof ResearchMethodologyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/research/changelog': {
      id: '/research/changelog'
      path: '/research/changelog'
      fullPath: '/research/changelog'
      preLoaderRoute: typeof ResearchChangelogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/research/2026-seoul-piano-academy-fees': {
      id: '/research/2026-seoul-piano-academy-fees'
      path: '/research/2026-seoul-piano-academy-fees'
      fullPath: '/research/2026-seoul-piano-academy-fees'
      preLoaderRoute: typeof Research2026SeoulPianoAcademyFeesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/research/2025-music-private-education-statistics': {
      id: '/research/2025-music-private-education-statistics'
      path: '/research/2025-music-private-education-statistics'
      fullPath: '/research/2025-music-private-education-statistics'
      preLoaderRoute: typeof Research2025MusicPrivateEducationStatisticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/media/$': {
      id: '/media/$'
      path: '/media/$'
      fullPath: '/media/$'
      preLoaderRoute: typeof MediaSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lessons/private': {
      id: '/lessons/private'
      path: '/lessons/private'
      fullPath: '/lessons/private'
      preLoaderRoute: typeof LessonsPrivateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lessons/home-visit': {
      id: '/lessons/home-visit'
      path: '/lessons/home-visit'
      fullPath: '/lessons/home-visit'
      preLoaderRoute: typeof LessonsHomeVisitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lessons/children': {
      id: '/lessons/children'
      path: '/lessons/children'
      fullPath: '/lessons/children'
      preLoaderRoute: typeof LessonsChildrenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lessons/adult': {
      id: '/lessons/adult'
      path: '/lessons/adult'
      fullPath: '/lessons/adult'
      preLoaderRoute: typeof LessonsAdultRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lessons/admission': {
      id: '/lessons/admission'
      path: '/lessons/admission'
      fullPath: '/lessons/admission'
      preLoaderRoute: typeof LessonsAdmissionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$category/': {
      id: '/blog/$category/'
      path: '/blog/$category'
      fullPath: '/blog/$category/'
      preLoaderRoute: typeof BlogCategoryIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$category/$slug': {
      id: '/blog/$category/$slug'
      path: '/blog/$category/$slug'
      fullPath: '/blog/$category/$slug'
      preLoaderRoute: typeof BlogCategorySlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRoute,
  EditorialPolicyRoute: EditorialPolicyRoute,
  LlmsDottxtRoute: LlmsDottxtRoute,
  PricingRoute: PricingRoute,
  PrivacyRoute: PrivacyRoute,
  RobotsDottxtRoute: RobotsDottxtRoute,
  RssDotxmlRoute: RssDotxmlRoute,
  SitemapRoute: SitemapRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  LessonsAdmissionRoute: LessonsAdmissionRoute,
  LessonsAdultRoute: LessonsAdultRoute,
  LessonsChildrenRoute: LessonsChildrenRoute,
  LessonsHomeVisitRoute: LessonsHomeVisitRoute,
  LessonsPrivateRoute: LessonsPrivateRoute,
  MediaSplatRoute: MediaSplatRoute,
  Research2025MusicPrivateEducationStatisticsRoute:
    Research2025MusicPrivateEducationStatisticsRoute,
  Research2026SeoulPianoAcademyFeesRoute:
    Research2026SeoulPianoAcademyFeesRoute,
  ResearchChangelogRoute: ResearchChangelogRoute,
  ResearchMethodologyRoute: ResearchMethodologyRoute,
  ResearchPianoSearchDemandReport2026Route:
    ResearchPianoSearchDemandReport2026Route,
  ResourcesPianoLevelRoadmapRoute: ResourcesPianoLevelRoadmapRoute,
  ResourcesPianoPracticePlannerRoute: ResourcesPianoPracticePlannerRoute,
  ToolsPianoChordChartRoute: ToolsPianoChordChartRoute,
  ToolsPianoLessonCostCalculatorRoute: ToolsPianoLessonCostCalculatorRoute,
  BlogIndexRoute: BlogIndexRoute,
  ResearchIndexRoute: ResearchIndexRoute,
  ResourcesIndexRoute: ResourcesIndexRoute,
  ToolsIndexRoute: ToolsIndexRoute,
  BlogCategorySlugRoute: BlogCategorySlugRoute,
  BlogCategoryIndexRoute: BlogCategoryIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
